# Campos do formulário: (label, key, unidade, placeholder)
FIELDS = [
    # Bioquímica e Função Renal/Hepática
    ("Glicose (GLU)", "GLU", "mg/dL", "ex: 96"),
    ("Ureia (URE)", "URE", "mg/dL", "ex: 42"),
    ("Creatinina (CRE)", "CRE", "mg/dL", "ex: 0.80"),
    ("Proteína C Reativa (PCR)", "PCR", "mg/dL", "ex: 0.40"),
    ("Cálcio total (CA)", "CA", "mg/dL", "ex: 9.6"),
    ("Fósforo (P)", "P", "mg/dL", "ex: 2.1"),
    ("AST / TGO (AST)", "AST", "U/L", "ex: 19"),
    ("ALT / TGP (ALT)", "ALT", "U/L", "ex: 14"),
    ("Fosfatase Alcalina (ALP/FA)", "ALP", "U/L", "ex: 76"),
    ("GGT (Gama-Glutamil Transferase)", "GGT", "U/L", "ex: 20"),
    ("Amilase (AML)", "AML", "U/L", "ex: 45"),
    ("Ferro sérico (FE)", "FE", "µg/dL", "ex: 102"),
    ("TIBC (Capacidade Total de Ligação do Ferro)", "TIBC", "µg/dL", "ex: 375"),
    ("Transferrina (TRF)", "TRF", "µg/dL", "ex: 262.5"),
    # Perfil Lipídico e Proteínas
    ("Colesterol Total (CT)", "CT", "mg/dL", "ex: 192"),
    ("Triglicerídeos (TG)", "TG", "mg/dL", "ex: 101"),
    ("HDL", "HDL", "mg/dL", "ex: 58"),
    ("VLDL", "VLDL", "mg/dL", "ex: 20"),
    ("LDL", "LDL", "mg/dL", "ex: 114"),
    ("Albumina (ALB)", "ALB", "g/dL", "ex: 4.62"),
    ("Proteínas Totais (PT)", "PT", "g/dL", "ex: 7.2"),
    ("Relação A/G (A/G)", "A_G", "razão", "ex: 1.48"),
    ("% Albumina na Eletroforese (%ALB)", "ALB_PCT", "%", "ex: 59.6"),
    ("Alfa-1 Globulina (α1)", "A1", "%", "ex: 3.5"),
    ("Alfa-2 Globulina (α2)", "A2", "%", "ex: 9.2"),
    ("Beta-1 Globulina (β1)", "B1", "%", "ex: 7.4"),
    ("Beta-2 Globulina (β2)", "B2", "%", "ex: 4.9"),
    ("Gama Globulina (γ)", "GAMMA", "%", "ex: 15.4"),
    # Hemograma e Marcadores Hematológicos
    ("Hemoglobina Glicada (HbA1c)", "HBA1C", "%", "ex: 4.8"),
    ("Hemácias / RBC / GR", "RBC", "10^6/mm3", "ex: 4.67"),
    ("Hemoglobina (HGB)", "HGB", "g/dL", "ex: 13.9"),
    ("Hematócrito (HCT)", "HCT", "%", "ex: 40.9"),
    ("VCM (MCV)", "MCV", "fL", "ex: 88"),
    ("HCM (MCH)", "MCH", "pg", "ex: 30"),
    ("CHCM (MCHC)", "MCHC", "g/dL", "ex: 34"),
    ("RDW", "RDW", "%", "ex: 13"),
    ("Leucócitos / WBC / GB", "WBC", "/mm3", "ex: 5960"),
    ("Bastonetes (Bands) %", "BAND", "%", "ex: 0"),
    ("Segmentados (Neutrófilos) %", "SEG", "%", "ex: 58"),
    ("Eosinófilos %", "EOS", "%", "ex: 6"),
    ("Basófilos %", "BASO", "%", "ex: 1"),
    ("Linfócitos Típicos %", "LYMPH", "%", "ex: 29"),
    ("Linfócitos Atípicos %", "LYMPH_ATYP", "%", "ex: 0"),
    ("Monócitos %", "MONO", "%", "ex: 6"),
    ("Plaquetas (PLT)", "PLT", "/mm3", "ex: 214000"),
    ("VPM (MPV)", "MPV", "fL", "ex: 10.5"),
    # Hormônios e Marcadores Endócrinos
    ("Estradiol (E2)", "E2", "pg/mL", "ex: 58.3"),
    ("FSH", "FSH", "mUI/mL", "ex: 8.38"),
    ("Insulina (INS)", "INS", "µUI/mL", "ex: 5.6"),
    ("HOMA-IR", "HOMA_IR", "índice", "ex: 1.32"),
    ("LH", "LH", "mUI/mL", "ex: 5.0"),
    ("PTH", "PTH", "pg/mL", "ex: 44.9"),
    ("Progesterona (PROG)", "PROG", "ng/mL", "ex: 0.39"),
    ("Prolactina (PRL)", "PRL", "ng/mL", "ex: 7.4"),
    ("Testosterona Total (TESTO)", "TESTO", "ng/dL", "ex: 20.12"),
    ("TSH", "TSH", "µUI/mL", "ex: 2.879"),
    ("T4 Livre (FT4)", "FT4", "ng/dL", "ex: 1.13"),
    ("Ácido Fólico (FOL/FA)", "FOLATE", "ng/mL", "ex: 14.3"),
    ("Anti-TPO", "ANTI_TPO", "UI/mL", "ex: 47.0"),
    ("Anti-Tg", "ANTI_TG", "UI/mL", "ex: 0.70"),
    # Marcadores Tumorais e Vitaminas
    ("CA 15-3", "CA15_3", "U/mL", "ex: 15.7"),
    ("CA 19-9", "CA19_9", "U/mL", "ex: 1.2"),
    ("Ferritina (FER)", "FER", "ng/mL", "ex: 45.3"),
    ("Vitamina B12 (B12)", "B12", "pg/mL", "ex: 719"),
    ("25-OH Vitamina D (VitD)", "VITD", "ng/mL", "ex: 54.56"),
    ("CEA", "CEA", "ng/mL", "ex: 0.8"),
    ("CA 125", "CA125", "U/mL", "ex: 10.5"),
    # Outros Hormônios e Marcadores
    ("Cortisol (COR)", "CORT", "µg/dL", "ex: 15.38"),
    ("Peptídeo C (C-PEP)", "C_PEP", "ng/mL", "ex: 1.70"),
    ("SHBG", "SHBG", "nmol/L", "ex: 41.3"),
    ("Testosterona Livre", "TESTO_FREE", "ng/dL", "ex: 0.34"),
    ("T3 Reverso (rT3)", "RT3", "ng/dL", "ex: 57.2"),
]

# Explicações breves por analito (para leigos)
EXPLAINS = {
    "GLU": "Açúcar no sangue; usado para diagnosticar e controlar diabetes.",
    "URE": "Produto do metabolismo; alto pode indicar rim sobrecarregado ou desidratação.",
    "CRE": "Avalia a função dos rins; sobe quando os rins filtram mal.",
    "PCR": "Proteína de inflamação; aumenta em infecções e inflamações.",
    "CA": "Mineral essencial para ossos e músculos; alterações sugerem problemas ósseos/renais/hormonais.",
    "P": "Mineral ligado a ossos e energia; fora do normal sugere alteração renal/óssea.",
    "AST": "Enzima de fígado e músculo; alta pode indicar lesão hepática ou muscular.",
    "ALT": "Enzima do fígado; alta sugere dano hepático.",
    "ALP": "Mede enzima relacionada a osso e fígado; alta pode indicar doença óssea ou biliar.",
    "GGT": "Enzima do fígado/vias biliares; alta sugere álcool excessivo ou doença hepática/biliar.",
    "AML": "Enzima do pâncreas; alta pode indicar pancreatite.",
    "FE": "Ferro no sangue; baixo causa anemia, alto pode indicar sobrecarga.",
    "TIBC": "Capacidade de transporte de ferro; ajuda a diferenciar tipos de anemia.",
    "TRF": "Proteína que carrega ferro; baixa pode indicar desnutrição ou inflamação.",
    "CT": "Gordura total no sangue; alto aumenta risco cardiovascular.",
    "TG": "Triglicerídeos; alto aumenta risco cardíaco e de pancreatite.",
    "HDL": "“Colesterol bom”; mais alto é melhor.",
    "VLDL": "Carrega triglicerídeos; alto indica risco metabólico.",
    "LDL": "“Colesterol ruim”; alto aumenta risco de entupimento das artérias.",
    "ALB": "Principal proteína do sangue; baixa sugere desnutrição ou doença hepática/renal.",
    "PT": "Soma das proteínas do sangue; avalia nutrição e fígado.",
    "A_G": "Relação albumina/globulinas; alterações sugerem inflamação ou doença hepática.",
    "ALB_PCT": "Percentual de albumina na eletroforese; baixo sugere perda ou produção reduzida.",
    "A1": "Fração de globulina; pode subir em inflamação aguda.",
    "A2": "Fração de globulina; aumenta em inflamação e algumas anemias.",
    "B1": "Fração de globulina; pode variar com lipídios e inflamação.",
    "B2": "Fração de globulina; pode subir em alterações lipídicas e inflamação.",
    "GAMMA": "Fração de anticorpos; alta em infecções crônicas e autoimunidade.",
    "HBA1C": "Média da glicose nos últimos ~3 meses; acompanha/diagnostica diabetes.",
    "RBC": "Quantidade de glóbulos vermelhos; baixa sugere anemia.",
    "HGB": "Proteína que carrega oxigênio; baixa indica anemia.",
    "HCT": "Porcentagem de células vermelhas no sangue; baixa em anemia.",
    "MCV": "Tamanho médio das hemácias; ajuda a classificar anemia.",
    "MCH": "Hemoglobina por célula; auxilia na tipagem da anemia.",
    "MCHC": "Concentração de hemoglobina nas hemácias; auxilia na tipagem.",
    "RDW": "Variação do tamanho das hemácias; alto sugere anemia ou deficiência de nutrientes.",
    "WBC": "Glóbulos brancos; avaliam infecções e inflamações.",
    "BAND": "Neutrófilos jovens (%); altos sugerem infecção aguda.",
    "SEG": "Neutrófilos maduros (%); sobem em infecção bacteriana.",
    "EOS": "Eosinófilos (%); sobem em alergias e parasitoses.",
    "BASO": "Basófilos (%); alterações são raras e ligadas a alergias.",
    "LYMPH": "Linfócitos (%); sobem em infecções virais.",
    "LYMPH_ATYP": "Linfócitos atípicos (%); vistos em algumas viroses.",
    "MONO": "Monócitos (%); sobem em inflamações crônicas.",
    "PLT": "Plaquetas; importantes para a coagulação.",
    "MPV": "Tamanho médio das plaquetas; indica produção/consumo.",
    "E2": "Estradiol; hormônio sexual que varia com sexo e ciclo.",
    "FSH": "Hormônio que regula ovários/testículos; avalia fertilidade e função gonadal.",
    "INS": "Hormônio que reduz a glicose; alto com glicose normal pode indicar resistência.",
    "HOMA_IR": "Estimativa de resistência à insulina.",
    "LH": "Estimula ovulação/testosterona; avalia função gonadal.",
    "PTH": "Regula cálcio e fósforo; avalia paratireoide.",
    "PROG": "Hormônio do ciclo/gestação; em homens é naturalmente baixo.",
    "PRL": "Hormônio da lactação; alto pode alterar ciclos e libido.",
    "TESTO": "Testosterona total; avalia função sexual e gonadal.",
    "TSH": "Hormônio que controla a tireoide.",
    "FT4": "Hormônio tireoidiano livre; mostra atividade da tireoide.",
    "FOLATE": "Vitamina B9; baixa causa anemia e sintomas neurológicos.",
    "ANTI_TPO": "Anticorpos contra a tireoide; altos sugerem autoimunidade.",
    "ANTI_TG": "Anticorpos contra tireoglobulina; indicam autoimunidade.",
    "CA15_3": "Marcador tumoral mamário; usado para acompanhamento.",
    "CA19_9": "Marcador tumoral digestivo; usado para acompanhamento.",
    "FER": "Ferritina, estoque de ferro; baixa em deficiência, alta em inflamação/sobrecarga.",
    "B12": "Vitamina B12; baixa causa anemia e alterações neurológicas.",
    "VITD": "Vitamina D; importante para ossos e imunidade.",
    "CEA": "Marcador tumoral; acompanhamento, especialmente no intestino.",
    "CA125": "Marcador tumoral ovariano; útil no acompanhamento.",
    "CORT": "Cortisol; hormônio do estresse que varia ao longo do dia.",
    "C_PEP": "Indica quanta insulina o corpo produz.",
    "SHBG": "Proteína que carrega hormônios sexuais; afeta a fração livre.",
    "TESTO_FREE": "Testosterona livre (ativa); reflete o que o corpo pode usar.",
    "RT3": "T3 reverso; avaliação complementar da tireoide.",
}
